name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta todos los d√≠as a medianoche UTC
  workflow_dispatch:      # Permite ejecutarlo manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Generar Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: iambraightondev
          svg_out_path: dist/snake.svg

      - name: Subir snake generado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Actualizando snake [bot]"
          add: "dist/snake.svg"
